// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oufgkwudphderhwmtxzv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im91Zmdrd3VkcGhkZXJod210eHp2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzkyNzc4NTYsImV4cCI6MjA1NDg1Mzg1Nn0.cLl-s7DcQyElaYE8wWluctLujH044Qd87yvd3m5dT-I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);